#configuration for eureka client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
  service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-57985744.okta.com/oauth2/default
    audience: api://default
